### PR TITLE
add notice regarding setImmediate

### PR DESCRIPTION
**Pull request by mikejw**
See issue: https://github.com/romgain/jest-websocket-mock/issues/122

### CODE REVIEW

**Review by romgain — APPROVED** [review]
Awesome, thanks!

**Comment by romgain** [comment]
Sorry @mikejw , would you mind running `npm run prettier:apply` in your branch to fix the CI?

**Comment by mikejw** [comment]
Sure, can do.

**Comment by mikejw** [comment]
Done

**Comment by romgain** [comment]
Thanks :)

**Pull request merged**
