### PR TITLE
Add optional `event` parameter to `WS#close`

### LINKED ISSUE #4: Rename `close` method to `tearDown`
The `close` method would be better suited as as `tearDown`.

This is b/c it calls `server.stop`, which removes the `WebSocket` reference.

This means the proper way to test close functionality is like so:

```
it('emits a "Close" event', () => {
  clientSocket.addListener(BSClientSocketEvent.Close, listener);

  ws.server.close({
    code: 3001,
    reason: 'no reason',
    wasClean: true
  });

  const expected: BSClientSocket.CloseEvent = {
    disconnectCode: 3001
  };

  expect(listener).toHaveBeenCalledTimes(1);
  expect(listener).toHaveBeenCalledWith(expected);
});
```

Meanwhile, `WS#close` should be used to clean up everything without having to worry about the details, such as in an `afterEach` block.

The `emit` should probably be removed too, since `server.close` already emits the proper `close` event.

### PR DESCRIPTION
**Pull request by G-Rath**
I opted to make the parameter both optional & `Partial`, for the sake of simplicity & ease-of-use. 

fixes #4

### CODE REVIEW

**Comment by romgain** [comment]
Hi @G-Rath, and thanks for your contribution!

The second argument to `server.emit` is just a data object, that gets packed into an actual event that is sent to the websocket client: https://github.com/thoov/mock-socket/blob/master/src/server.js#L122-L158

You can also see that by logging the event in the close callback in this test: https://github.com/romgain/jest-websocket-mock/blob/master/src/__tests__/websocket.test.ts#L128

Are you suggesting this change because you rely on custom close events that you want to test? 
If that's the case, then I believe the argument to WS.close should be a `data: any`. But it would help to know more about your use case! :slightly_smiling_face:

**Comment by G-Rath** [comment]
Right.

I'm still trying to wrap my head around how this is actually working (i.e its difference to an object composed of `jest.fn` functions).

I don't think it should be `any`, as there are clearly defined properties to the data object included in the `close` event. However, it could have an index signature of type `any`, to allow additional properties.

This is my test case:

```
it('emits a "Close" event', async () => {
  clientSocket.addListener(BSClientSocketEvent.Close, listener);

  ws.close();

  const expected: BSClientSocket.CloseEvent = expect.objectContaining({
    // todo: should be expect.any(Number) once https://github.com/romgain/jest-websocket-mock/issues/4 is fixed
    disconnectCode: undefined
  });

  expect(listener).toHaveBeenCalledTimes(1);
  expect(listener).toHaveBeenCalledWith(expected);
});
```

This is the method from the class its testing:

```
    /**
     * Handles when the websocket receives a close event.
     *
     * @param {CloseEvent} closeEvent
     *
     * @fires BSClientSocketEvent#Close
     * @private
     */
    private _handleSocketClosed(closeEvent: CloseEvent) {
        this.emit(BSClientSocketEvent.Close, { disconnectCode: closeEvent.code });
    }
```

**Comment by G-Rath** [comment]
I feel silly b/c I completely missed that `server` is public :joy:

I think this PR could have value, but tbh now I actually feel maybe it should be renamed to something like 'packdown', given that it also calls `stop`.

I have this test:

```
it('throws "SocketNotReadyException"', () => {
  ws.close();

  expect(
    () => clientSocket.sendMessageToServer('handshake', { userId: '' })
  ).toThrow(SocketNotReadyException);
});
```

This would error b/c by calling `this.server.stop();` `WebSocket` went away, so when the class did `this._socket.readyState !== WebSocket.OPEN`, it'd throw due to `WebSocket` no longer being defined.

Hence that makes me feel like `WS.close` is more of a `packdown` method meant to be called in `afterAll`, rather than to be used in tests themselves for testing?

Feel free to correct me on that if I'm wrong :)

**Comment by romgain** [comment]
Right, I think I'm starting to understand your use case.
The `server` is indeed exposed as an escape hatch for this kind of interactions, while `.close` is here as a more convenient way to close everything down without having to worry about the details (perfect in an `afterAll` block as you said!)

I have a feeling that the second argument to `emit` won't really let you do what you want though(?) It looks like it gets stringified and directly passed in the event. This might be an issue with MockSocket though.

I tried replicating this in the unit test I linked above (including your changes):

```diff
diff --git a/src/__tests__/websocket.test.ts b/src/__tests__/websocket.test.ts
index 277a9b1..ac34677 100644
--- a/src/__tests__/websocket.test.ts
+++ b/src/__tests__/websocket.test.ts
@@ -124,14 +124,22 @@ describe("The WS helper", () => {
     const client = new WebSocket("ws://localhost:1234");
     await server.connected;

+    let closeEvent: any;
     let disconnected = false;
-    client.onclose = () => {
+    client.onclose = e => {
       disconnected = true;
+      closeEvent = e;
     };

     server.send("hello everyone");
-    server.close();
+    server.close({ disconnectCode: 42 });
     expect(disconnected).toBe(true);
+    expect(closeEvent).toEqual(
+      expect.objectContaining({
+        data: { disconnectCode: 42 },
+      })
+    );
+    expect(closeEvent.type).toBe("close");
   });
```

And here's the test result:

```
 FAIL  src/__tests__/websocket.test.ts                                                                                                                                                            
  ● The WS helper › closes the connection                                                                                                                                                         
                                                                                                                                                                                                  
    expect(received).toEqual(expected)                                                                                                                                                            
                                                                                                                                                                                                  
    Difference:                                                                                                                                                                                   
                                                                                                                                                                                                  
    - Expected                                                                                                                                                                                    
    + Received                                                                                                                                                                                    
                                                                                                                                                                                                  
    - ObjectContaining {                                                                                                                                                                          
    -   "data": Object {                                                                                                                                                                          
    -     "disconnectCode": 42,                                                                                                                                                                   
    + MessageEvent {                                                                                                                                                                              
    +   "bubbles": false,                                                                                                                                                                         
    +   "cancelable": false,                                                                                                                                                                                                                                                                                                               
<lots more>
    +   "data": "[object Object]",                                                                                                                                                                
    +   "defaultPrevented": false,                                                                                                                                                                
  +   "type": "close",
      }

      at toEqual (src/__tests__/websocket.test.ts:137:24)
```

**Comment by G-Rath** [comment]
> It looks like it gets stringified and directly passed in the event. This might be an issue with MockSocket though.

Maybe.

But I think the situation here is that I should just be calling `server.close` directly - that method actually takes `CloseOptions` as a parameter, and emits the correct `close` event:

```
  interface CloseOptions {
    code: number;
    reason: string;
    wasClean: boolean;
  }
```

Again, this is all making me feel like your `close` is really a `packdown`.

**Comment by romgain** [comment]
Yes and yes :slightly_smiling_face: 

While I agree with you, I don't really want to rename `close` as that would be a breaking change. 
Should we close this for now and re-open should there be other reasons to release a v2?

**Comment by G-Rath** [comment]
> While I agree with you, I don't really want to rename close as that would be a breaking change.

Totally! One thing you could do is rename it, but create an alias (i.e `close` which calls `packDown`), and then mark it with `@deprecated` and remove in v2.

> Should we close this for now and re-open should there be other reasons to release a v2?

I think that might be best. I wouldn't close the issue however, and I'd mark both PR & issue with a tag like "Breaking Change".

**Comment by romgain** [comment]
I think the change would require a bit more work than what's on this PR, so I'll close it for now. We can always re-open it if we want to.

Also #4 is not really accurate anymore - would you mind renaming it and updating the description to capture what we discussed here?

(And `tearDown` would have my preference over `packDown` :slightly_smiling_face:)

Thanks again for your contributions, it's really appreciated!

**Comment by G-Rath** [comment]
> (And tearDown would have my preference over packDown 🙂)

Agreed, much better.

> Also #4 is not really accurate anymore - would you mind renaming it and updating the description to capture what we discussed here?

I'll do that tomorrow morning if its alright with you - it's 1am on Sunday here, and I've been coding all day :joy:

**Comment by romgain** [comment]
Of course! :smile:

**Comment by G-Rath** [comment]
I'm just doing a cleanup of my account, deleting some old forks.

It's been a while since I've worked w/ WebSockets, and can't even remember what this was about, but just in case deleting the fork prevents this PR from being re-opened, here it is in fake git diff form:

```
diff --git a/src/websocket.ts b/src/websocket.ts
--- a/src/websocket.ts
+++ b/src/websocket.ts
@@ -62,8 +62,8 @@ export default class WS {
    this.server.emit("message", this.serializer(message));
  }

- close() {
-  this.server.emit("close", null);
+ close(event: Partial<CloseEvent> = {}) {
+   this.server.emit("close", event);
    this.server.stop();
    this.server.close();
  }
```

**Pull request closed without merging**
