### PR TITLE
1.1.2

### PR DESCRIPTION
**Pull request by ruslanchek**
Server: onMessage method added

### CODE REVIEW

**Comment by romgain** [comment]
Thanks for contributing @ruslancheck!

Would you mind explaining the idea behind that change? I was hoping that higher level assertions, like `toReceiveMessage`, would cover most use cases. 

Could you maybe share the code you're trying to test? It might be that we need to add more custom matchers, or that the docs need updating!

Thanks!

**Comment by ruslanchek** [comment]
Hi! In my case i was needed need to define some "server logic" to respond to clients' requests. Here is an example:

```javascript
const items = [];

server.onMessage(message => {
  switch(message.action) {
    case 'getItems' : {
      server.send({
        items,
      });
    }

    case 'addItem' : {
      items.push(message.item);
    }
  }
})
```

**Comment by romgain** [comment]
Is there a reason not to directly call `ws.send(...)` in your unit test?

If you're testing client code, there shouldn't be a need to replicate the backend functionality (and state) in your test?

I'd like to keep jest-websocket-mock a thin assertion library, used to check client behaviours: what messages they send, and their behaviour when receiving messages. 

I don't think that the backend implementation should be a concern for this library.

If you need more control, maybe hooking into the `ws.server` (or directly using the mock-socket library) is what you want?

We can always make the server instance on the `WS` object configurable if that would help.

**Comment by ruslanchek** [comment]
WebSocket way can handle subscriptions not only request-respond communication. I making a library that have it's own protocol for subscriptions and i have to test that subscriptions flow working as it designed.

**Comment by ruslanchek** [comment]
Thank you! Maybe you could show me (or add to documentation) some examples how to test subscriptions workflow? 

I need to test something like that:
Client sent subscription request:
`{action: "getItems", pid: 1, subscription: true}`
Server respond: 
`{items: [...], pid: 1, subscriptionId: 123}`
...some time after server respond again
`{items: [...], subscriptionId: 123}`

The problem is that second event fires asynchronously and i can't catch it in client-side code and test failing

**Comment by romgain** [comment]
Since this library fully mocks out the backend, this is probably how I'd write these tests:


```js
it("subscribes correctly", async () => {
  client.startTheSubscription();
  await expect(ws).toReceiveMessage({action: "getItems", pid: 1, subscription: true});
  ws.send({items: ["x"], pid: 1, subscriptionId: 123});
  expect(client.state.items).toEqual(["x"]);
  ws.send({items: ["x", "y"], subscriptionId: 123});
  expect(client.state.items).toEqual(["x", "y"]);
});
```

The idea is to only run expectations on the client state, or what messages the mock server receives. 
Asynchronous behaviours are handled by waiting for the mock server to receive messages. The backend is fully mocked out, therefore completely synchronous.


Does the example app (and the associated tests, like https://github.com/romgain/jest-websocket-mock/blob/master/examples/src/__tests__/saga.test.js#L31 ) help at all? Or are is it too simple to be useful?

**Comment by ruslanchek** [comment]
I think it would be helpful enough! Thanks!

**Pull request closed without merging**
