### PR TITLE
Use optional generics in expect matchers

### LINKED ISSUE #7: Use optional generics in expect matchers
This is change I've suggested for the actual [`jest` typings](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34522) as well.

Basically, if you defined your matchers with generics, it'll let us explicitly denote the expected type, and benefit from both autocompletion & strong typing:

```
toReceiveMessage<TMessage = object>(message: DeserializedMessage<TMessage>): R;
toHaveReceivedMessages<TMessage = object>(messages: Array<DeserializedMessage<TMessage>>): R;
```

This would result in `DeserializedMessage` becoming generic as well:

```
export type DeserializedMessage<TMessage = object> = string | TMessage;
```

Use case:

ss+(2019-04-06+at+11 14 41)

```
it('sends the message', () => {
  const requestType: BotSocket.RequestType = 'handshake';
  const requestData: BotSocket.ClientHandshakeData = {
    userId: 'client-1'
  };

  clientSocket.sendMessageToServer(requestType, requestData);

  expect(ws).toHaveReceivedMessages<BotSocket.Message>([
    {
      request: 'handshake',
      data: {
        userId: 'hello world'
      }
    }
  ]);
});
```

I'm happy to make a PR if you're happy to merge it 😄

### PR DESCRIPTION
**Pull request by G-Rath**
fixes #7

### CODE REVIEW

**Comment by G-Rath** [comment]
@romgain I have no idea how changing the typing could affect the cli, since there you're not using anything like `dts-jest` O.o

**Comment by romgain** [comment]
Can't you see https://travis-ci.org/romgain/jest-websocket-mock/jobs/516684080 ? Everything should be public in Travis. Let me know if it's not and I'll fiddle with the settings.

It's just a formatting issue (we use prettier to format this codebase). You should be able to run `npm run prettier:apply` to fix the issue.

I raised #11 to add a contributing guide to document this - and anything else that would make contributing easier. It would be great if you could add you thoughts on that issue: anything that wasn't clear or that we could add to that would have made your contributions easier. Thanks! :slightly_smiling_face:

**Comment by G-Rath** [comment]
Weirdly when I run prettier I get an error:

```
> jest-websocket-mock@1.2.0 prettier:apply C:\Users\G-Rath\workspace\projects-personal\jes
t-websocket-mock
> prettier --write 'src/**/*.{ts,js}'

[error] No matching files. Patterns tried: 'src/**/*.{ts,js}' !**/node_modules/** !./node_
modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**
```

**Comment by romgain** [comment]
I pushed https://github.com/romgain/jest-websocket-mock/commit/ffc6e40d12c555bbd4e204f0b94f3500f4dbcf70 which should fix the prettier scripts for you. Let me know if it still doesn't work.

**Pull request merged**
